app/Http/routes.php
<?php

/** ============ NEUTRAL AREA ============ */

// Main page
get('/', ['as' => 'home', 'uses' => 'HomeController@showHomePage']);

// Change current language
get('lang/{code}', ['as' => 'language.set', 'uses' => 'HomeController@changeApplicationLanguage']);

/** ============ ONLY GUESTS AREA ============ */

Route::group(['https', 'middleware' => 'guest'], function () {

	// Login page
	get('login', ['as' => 'login', 'uses' => 'AuthController@showLoginPage']);

	// Login with social provider
	get('login/{provider}', ['as' => 'login.with', 'uses' => 'AuthController@loginWithProvider']);
});

/** ============ ONLY AUTHENTICATED USERS AREA ============ */

Route::group(['https', 'middleware' => 'auth'], function () {

	// Logout
	get('logout', ['as' => 'logout', 'uses' => 'AuthController@logout']);

	/** ============ ONLY GRANTED USERS AREA ============ */

	Route::group(['middleware' => 'permissions'], function () {

		// RESTful resources
		Route::resource('category', 'CategoryController');
		Route::resource('language', 'LanguageController');
		Route::resource('page', 'PageController');
		Route::resource('page.version', 'VersionController', ['only' => ['index', 'show']]);
		Route::resource('provider', 'ProviderController');
		Route::resource('role', 'RoleController');
		Route::resource('user', 'UserController');

	});
});

app/Version.php
<?php namespace App;

use Request;
use Illuminate\Database\Eloquent\Model;

class Version extends Model
{
	// Meta ========================================================================

	/**
	 * The attributes that are not mass-assignable.
	 *
	 * @var array
	 */
	protected $guarded = ['*'];

	/**
	 * What should be returned when this model is converted to string.
	 *
	 * @return string
	 */
	public function __toString()
	{
		return (string) $this->name;
	}

	/**
	 * Get the human-friendly singular name of the resource.
	 *
	 * @return string
	 */
	protected function getSingularAttribute()
	{
		return _('Version');
	}

	/**
	 * Get the human-friendly plural name of the resource.
	 *
	 * @return string
	 */
	protected function getPluralAttribute()
	{
		return _('Versions');
	}

	// Relationships ===============================================================

	public function page()
	{
		return $this->belongsTo('App\User');
	}

	public function user()
	{
		return $this->belongsTo('App\User');
	}

	// Events ======================================================================

	// Static Methods ==============================================================

	/**
	 * Create version from existing page.
	 *
	 * @return bool
	 */
	public static function createFromPage(Page $page)
	{
		$version = new static;
		$version->name = $page->name;
		$version->source = $page->source;
		$version->ip_address = Request::getClientIp();
		$version->page_id = $page->id;
		$version->user_id = auth()->user()->id;

		return $version->save();
	}

	// Bussiness logic =============================================================
}

app/Http/Controllers/VersionController.php
<?php namespace App\Http\Controllers;

use App\Page;
use App\Version;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use URL;

class VersionController extends Controller
{
	/**
	 * Display a listing of versions of a page.
	 *
	 * @param  integer
	 * @return Response
	 */
	public function index($pageId)
	{
		// Make sure page exists
		$page = Page::findOrFail($pageId);

		// Load view
		return view('version.index', [
			'title' => _('Versions'),
			'subtitle' => $page,
			'versions' => $page->versions()->latest()->with('user')->paginate(),
			'compareUrl' => route('page.version.show', [$page->id]),
			'returnUrl' => (false !== strpos(URL::previous(), '?page=')) ? URL::previous() : route('page.show', [$page->id]),
		]);
	}

	/**
	 * If one version is provided, show version.
	 * If two versions are provide, compare them.
	 *
	 * @param  int      $pageId
	 * @param  string   $versionIds
	 * @return Response
	 */
	public function show($pageId, $versionIds)
	{
		// Make sure page exists
		$page = Page::findOrFail($pageId);

		// Make sure no more than two version ids are used
		$versionIds = array_slice(explode('-', $versionIds), 0, 2);

		// Get versions with oldest first
		$versions = $page->versions()->whereIn('id', $versionIds)->oldest()->with('user')->get();

		$count = $versions->count();

		if($count === 0)
			throw with(new ModelNotFoundException)->setModel('App\Version');

		// Compare versions
		if($count === 2)
			return $this->compareVersions($versions->first(), $versions->last());

		// Show single version
		return view('version.show', [
			'version'  => $version = $versions->first(),
			'title'    => $version->singular,
			'subtitle' => $version->name,
		]);
	}

	/**
	 * Show difference between two versions.
	 *
	 * @param  \App\Version
	 * @param  \App\Version
	 * @return void
	 */
	protected function compareVersions(Version $before, Version $after)
	{
		// Parse source
		$beforeArray = explode("\n", $before->source);
		$afterArray = explode("\n", $after->source);

		// Compare versions
		$diff = new \Diff($beforeArray, $afterArray, $options = [
			//'context' => 3,
			//'ignoreNewLines' => false,
			//'ignoreWhitespace' => false,
			//'ignoreCase' => false
		]);

		// Load view
		return view('version.compare', [
			'title' => _('Versions'),
			'subtitle' => _('Compare'),
			'before' => $before,
			'after' => $after,
			'sideBySideDiff' => $diff->Render(new \Diff_Renderer_Html_SideBySide),
			'inlineDiff' => $diff->render(new \Diff_Renderer_Html_Inline),
		]);
	}
}

resources/views/version/compare.blade.php
@extends('layouts.master')

<?php Assets::add('diff.css') ?>

@section('content')

	<h3 class="text-center">{{ $subtitle }}</h3>


		{{-- FACTS --}}
		<div class="row">
			<div class="small-6 columns">
				<ul class="pricing-table">
					<li class="title">{{ _('Before') }}</li>
					<li class="price">{{ $before->name }}</li>
					<li class="description">{{ _('Created by') }}: {{ $before->user }}</li>
					<li class="bullet-item">{{ $before->created_at }} {{ $before->created_at->diffForHumans() }}</li>
					<li class="cta-button"><a class="button" href="TODO">{{ _('Restore') }}</a></li>
				</ul>
			</div>

			<div class="small-6 columns">
				<ul class="pricing-table">
					<li class="title">{{ _('After') }}</li>
					<li class="price">{{ $after->name }}</li>
					<li class="description">{{ _('Created by') }}: {{ $after->user }}</li>
					<li class="bullet-item">{{ $after->created_at }} {{ $after->created_at->diffForHumans() }}</li>
					<li class="cta-button"><a class="button" href="TODO">{{ _('Restore') }}</a></li>
				</ul>
			</div>
		</div>

		{{-- TAB BUTTONS --}}
		<ul class="tabs button-group even-2" data-tab>
			<li class="active"><a href="#panel1" class="secondary button">{{ _('Side by side') }}</a></li>
			<li><a href="#panel2" class="secondary button">{{ _('Inline') }}</a></li>
		</ul>

		{{-- TABS --}}
		<div class="tabs-content">
			<div class="content active" id="panel1">
				{!! $sideBySideDiff !!}
			</div>

			<div class="content" id="panel2">
				{!! $inlineDiff !!}
			</div>

		</div>

	<p class="text-center">
		{!! link_to_route('page.version.index', _('Return'), [$before->page_id], ['class' => 'secondary button']) !!}
	</p>

@stop

resources/views/version/index.blade.php
@extends('layouts.master')

@section('content')

	<h3 class="text-center">{{ $subtitle }}</h3>

	@if ($versions->count())

	<table summary="" style="margin-left: auto;margin-right: auto">

		<thead>
			<tr>
				<th class="text-center">{{ _('Compare') }}</th>
				<th class="text-center">{{ _('Title') }}</th>
				<th class="text-center">{{ _('Date') }}</th>
				<th class="text-center">{{ _('By') }}</th>
			</tr>
		</thead>

		<tbody>
			@foreach ($versions as $v)
			<tr>
			<td class="text-center">
					<input type="radio" name="a" value="{{$v->id}}"/>
					<input type="radio" name="b" value="{{$v->id}}"/>
				</td>
				<td>{!! link_to_route('page.version.show', $v->name, [$v->page_id, $v->id]) !!}</td>
				<td>
					{{ $v->created_at->toDayDateTimeString() }}<br/>
					{{ $v->created_at->diffForHumans() }}
				</td>
				<td>{{ $v->user }}</td>
			</tr>
			@endforeach
		</tbody>

	</table>

		{!! pagination_links($versions) !!}
	@else
		<div class="alert-box alert" data-alert>
		{{ _('No results found') }}
		<a class="close">&times;</a>
		</div>
	@endif

	<p class="text-center">
		{!! link_to($compareUrl, _('Compare'), ['id' => 'compare', 'class' => 'button']) !!}
		{!! link_to($returnUrl, _('Return'), ['class' => 'secondary button']) !!}
	</p>

@stop


@section('js')
@parent
<script>
$(document).ready(function() {

	$('#compare').click(function(e) {
		var a = $('input[name=a]:checked').val();
		var b = $('input[name=b]:checked').val();

		if( ! parseInt(a) || ! parseInt(b))
			return e.preventDefault();

		$(this).prop('href', $(this).prop('href') + '/' + a + '-' + b);
	});

});
</script>
@stop

resources/views/version/show.blade.php
@extends('layouts.master')

@section('content')

	<p class="text-center">
		<i>{{ sprintf(_('Version created by %s on %s (%s)'), $version->user, $version->created_at->toDayDateTimeString(), $version->created_at->diffForHumans()) }}</i>
	</p>

	<h3 class="text-center">{{ $subtitle }}</h3>

	{!! markup($version->source) !!}

	<p class="text-center">
		{!! link_to_route('page.version.index', _('Return'), [$version->page_id], ['class' => 'secondary button']) !!}
	</p>

@stop