app/Http/routes.php
<?php

/** ============ NEUTRAL AREA ============ */

// Main page
get('/', ['as' => 'home', 'uses' => 'HomeController@showHomePage']);

// Change current language
get('lang/{code}', ['as' => 'language.set', 'uses' => 'HomeController@changeApplicationLanguage']);

/** ============ ONLY GUESTS AREA ============ */

Route::group(['https', 'middleware' => 'guest'], function () {

	// Login page
	get('login', ['as' => 'login', 'uses' => 'AuthController@showLoginPage']);

	// Login with social provider
	get('login/{provider}', ['as' => 'login.with', 'uses' => 'AuthController@loginWithProvider']);
});

/** ============ ONLY AUTHENTICATED USERS AREA ============ */

Route::group(['https', 'middleware' => 'auth'], function () {

	// Logout
	get('logout', ['as' => 'logout', 'uses' => 'AuthController@logout']);

	/** ============ ONLY GRANTED USERS AREA ============ */

	Route::group(['middleware' => 'permissions'], function () {

		// RESTful resources
		Route::resource('category', 'CategoryController');
		Route::resource('language', 'LanguageController');
		Route::resource('page', 'PageController');
		Route::resource('page.version', 'VersionController', ['only' => ['index', 'show']]);
		Route::resource('provider', 'ProviderController');
		Route::resource('role', 'RoleController');
		Route::resource('user', 'UserController');

	});
});

app/Category.php
<?php namespace App;

use Baum\Node as Model;

class Category extends Model
{
	// Meta ========================================================================

	/**
	 * The attributes that are not mass-assignable.
	 *
	 * @var array
	 */
	protected $guarded = ['id', 'parent_id', 'lft', 'rgt', 'depth', 'created_at', 'updated_at'];

	/**
	 * Column to perform the default sorting
	 *
	 * @var string
	 */
	protected $orderColumn = 'name';

	/**
	 * What should be returned when this model is converted to string.
	 *
	 * @return string
	 */
	public function __toString()
	{
		return (string) $this->name;
	}

	/**
	 * Get the human-friendly singular name of the resource.
	 *
	 * @return string
	 */
	protected function getSingularAttribute()
	{
		return _('Category');
	}

	/**
	 * Get the human-friendly plural name of the resource.
	 *
	 * @return string
	 */
	protected function getPluralAttribute()
	{
		return _('Categories');
	}

	// Relationships ===============================================================

	public function pages()
	{
		return $this->hasMany('App\Page');
	}

	// Events ======================================================================

	// Static Methods ==============================================================

	/**
	 * Get all categories in a unidimensional array, ideal for being used in a form select dropdown.
	 *
	 * @param  boolean
	 * @return array
	 */
	public static function dropdown($includeRootNode = true)
	{
		$categories = self::getNestedList('name', null, '--');

		return ($includeRootNode) ? ['' => _('Root')] + $categories : $categories;
	}

	// Bussiness logic =============================================================
}

app/Http/Controllers/CategoryController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests\CreateCategoryRequest as CreateRequest;
use App\Http\Requests\CreateCategoryRequest as UpdateRequest;
use App\Category as Model;
use App\Page;

class CategoryController extends ResourceController
{
	/**
	 * Class constructor.
	 *
	 * @param  Model
	 * @return void
	 */
	public function __construct(Model $resource)
	{
		parent::__construct($resource);
	}

	/**
	 * Display a tree of all categories.
	 *
	 * @param  Paginator
	 * @return Response
	 */
	public function index($resources = null)
	{
		// HTML of a tree node
		$template = view($this->directory . '.node')->withRoute($this->route)->render();

		// Function to render a tree node
		$render = function (array $node) use ($template) {
			$template = str_replace('_id_', $node['id'], $template);

			return str_replace('_name_', $node['name'], $template);
		};

		// Get categories hierarchy
		$hierarchy = $this->resource->all()->toHierarchy()->toArray();

		// Split hierarchy into chunks of root nodes
		$chunks = array_chunk($hierarchy, 1);

		// Add one tree per chunk
		$trees = [];
		foreach($chunks as $chunk)
			$trees[] = tree($chunk, $render);

		// Load view
		return view($this->directory . '.index', [
			'title' => _('Categories'),
			'subtitle' => _('Index'),
			'trees' => $trees,
		]);
	}

	/**
	 * Display the subtree of a category.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		// Make sure resource exists
		$this->resource = $this->resource->findOrFail($id);
		$this->subtitle = $this->resource;

		// Get subcategories
		$subcategories = $this->resource->getDescendants();

		// Get pages this category
		$pages = $this->resource->pages()->orderBy('name')->get();

		// Get pages of subcategories
		$subpages = Page::whereIn('category_id', $subcategories->lists('id'))->orderBy('name')->get();

		// Function to render a tree node
		$render = function (array $node) {
			return link_to_route('category.show', $node['name'], [$node['id']]);
		};

		// Build subcategories tree
		$tree = tree($subcategories->toHierarchy()->toArray(), $render);

		view()->share(compact('pages', 'subpages', 'subcategories', 'tree'));

		return parent::show($id);
	}

	/**
	 * Create a new resource.
	 *
	 * @param  CreateRequest
	 * @return Response
	 */
	public function store(CreateRequest $request)
	{
		// The 'parent_id' attribute is guarded so it will be ignored and
		// the node will be saved as a root node
		$response = parent::_store($request);

		// If 'parent_id' was provided attach the newly created node to the provided parent
		if($parentId = intval($request->input('parent_id')))
			$this->resource->makeChildOf(Model::findOrFail($parentId));

		return $response;
	}

	/**
	 * Update an exsiting resource.
	 *
	 * @param  UpdateRequest
	 * @param  int $id
	 * @return Response
	 */
	public function update(UpdateRequest $request, $id)
	{
		// The 'parent_id' attribute is guarded so it will be ignored and
		// the node hierarchy will not be altered.
		$response = parent::_update($request, $id);

		// If no 'parent_id' was provided it means the resource is a root node
		if($parentId = intval($request->input('parent_id')))
			$this->resource->makeChildOf(Model::findOrFail($parentId));
		else
			$this->resource->makeRoot();

		return $response;
	}

	/**
	 * Display a form for saving a resource.
	 *
	 * @param  string $subtitle Page subtitle.
	 * @param  string $action   Form route sufix.
	 * @param  string $method   Form method.
	 * @return Response
	 */
	protected function showForm($subtitle, $action, $method = 'POST')
	{
		view()->share('categories', \App\Category::dropdown());

		return parent::showForm($subtitle, $action, $method);
	}

	/**
	 * Remove the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		// Make sure resource exists
		$resource = $this->resource->findOrFail($id);

		// Move pages to the parent
		if(with($pages = $resource->pages)->count())
		{
			// Check if there is actually a parent category to be used as destination
			if($resource->isRoot())
			{
				Session::flash('error', _('The category cannot be deleted because it has directly assigned pages'). '. '. _('Please move those pages to another category first'));

				return redirect()->back()->withInput();
			}

			Page::where('category_id', $resource->id)->update(['category_id' => $resource->parent->id]);
		}

		// Move subcategories to the parent
		foreach($resource->children as $children)
			($resource->isRoot()) ? $children->makeRoot() : $children->makeChildOf($resource->parent);

		return parent::destroy($id);
	}
}

resources/views/category/form.blade.php
<div class="row">
	<div class="small-11 medium-6 large-5 small-centered columns">

	{!!
		Form::label('parent_id', _('Parent')),
		Form::select('parent_id', $categories, Input::get('parent_id')),

		Form::label('name', _('Name')),
		Form::text('name')
	!!}

	</div>

</div>

resources/views/category/index.blade.php
@extends('layouts.master')

@section('content')

	<h3 class="text-center">{{ $subtitle }}</h3>

	<ul class="small-block-grid-1 medium-block-grid-2 large-block-grid-3">
		@foreach($trees as $tree)
		<li><div class="panel">{!! $tree !!}</div></li>
		@endforeach
	</ul>

	<p class="text-center">
		{!! link_to_route("$route.create", _('Create'), [], ['class' => 'success button']) !!}
	</p>

@stop

resources/views/category/node.blade.php
<a data-dropdown="drop_id_" class="secondary label" data-options="align:left">+</a>

<a href="{{ route("$route.show", ['_id_']) }}">_name_</a>

<div id="drop_id_" class="f-dropdown small content" data-dropdown-content>
	{!! link_to_route("$route.create", _('Create'), ['parent_id' => '_id_'], ['class' => 'tiny success button']) !!}
	{!! link_to_route("$route.edit", _('Edit'), ['_id_'], ['class'=>'tiny button']) !!}
	{!! link_to_route('page.create', _('Add page'), ['category_id' => '_id_'], ['class' => 'tiny secondary button']) !!}
</div>

resources/views/category/show.blade.php
<div class="row">

	{{-- PAGES --}}
	<div class="medium-6 columns">
		<div class=" panel">
			<h5 class="text-center">{{ _('Pages') }}</h5>

			@if ($pages->count())
				<ul class="side-nav">
					@foreach ($pages as $page)
						<li>{!! link_to_route('page.show', $page, [$page->getKey()]) !!}</li>
					@endforeach
				</ul>
			@else
				<p class="text-center">
					{{ _('This category has no pages yet') }}
				</p>
			@endif

			@if ($subpages->count())
				<hr/>
				<h5 class="text-center">{{ _('Pages on subcategories') }}</h5>
				<ul class="side-nav">
					@foreach ($subpages as $page)
						<li>{!! link_to_route('page.show', $page, [$page->getKey()]) !!}</li>
					@endforeach
				</ul>
			@endif

			<p class="text-center">
				{!! link_to_route('page.create', _('Create page'), ['category_id' => $resource->getKey()], ['class' => 'small success button']) !!}
			</p>

		</div>
	</div>

	{{-- SUBCATEGORIES --}}
	<div class="medium-6 columns">
		<div class="callout panel">
			<h5 class="text-center">{{ _('Subcategories') }}</h5>

			@if ($subcategories->count())
				{!! $tree !!}
			@else
				<p class="text-center">
					{{ _('This category has no subcategories') }}
				</p>
			@endif

			<p class="text-center">
				{!! link_to_route("$route.create", _('Create subcategory'), ['parent_id' => $resource->getKey()], ['class' => 'small success button']) !!}
			</p>

		</div>
	</div>

</div>